from __future__ import annotations

from pathlib import Path
import sys

if getattr(sys, "frozen", False):
    PROJECT_ROOT = Path(sys.executable).resolve().parent
else:
    PROJECT_ROOT = Path(__file__).resolve().parent.parent

WAYPOINT_CHUNK_SIZE = 2048.0
WAYPOINT_ICON_SCALE_SWITCH = 0.32
WAYPOINT_HIDE_NAMES_SCALE = 0.35
MAX_VISIBLE_ICON_MARKERS = 60000
MAX_VISIBLE_POINT_MARKERS = 20000
MAX_WAYPOINT_LIST_ITEMS = 1500
POINT_OVERLAY_DOWNSCALE = 2
POINT_OVERLAY_DOWNSCALE_HEAVY = 3
MAX_TILE_TEXTURES = 160
VISIBLE_TILE_MARGIN = 2
TILE_KEEP_EXTRA_MARGIN = 2
MARKER_TILE_MARGIN = 0
MAX_MARKERS_ON_SCREEN = 10000
SQUARE_RENDER_THRESHOLD = 5000
DEFAULT_IMAGE_RESOLUTION = 256
DEFAULT_MAX_GENERATED_MARKERS = 6000
INTERACTION_GRACE_FRAMES = 8
INTERACTION_POINT_BUDGET = 5000
SELECTION_CLICK_TOLERANCE_SCREEN_PX = 6.0
INITIAL_ZOOM = 0.05
DEFAULT_MAP_ZOOM_MULTIPLIER = 1.12
DEFAULT_MARKER_ZOOM_MULTIPLIER = 2.05
IMAGE_PREVIEW_TEXTURE_MAX_DIM = 1024
IMAGE_AUTO_RESOLUTION_MAX_DIM = 1024
IMAGE_PREVIEW_MIN_SIZE_MAP_PX = 64.0
IMAGE_PREVIEW_HANDLE_SCREEN_PX = 10.0
UNDO_HISTORY_LIMIT = 40
DEFAULT_ALPHA_CUTOFF = 22
DEFAULT_BRIGHTNESS_CUTOFF = 0
DEFAULT_CONTOUR_THICKNESS = 1
DEFAULT_CONTOUR_EDGE_THRESHOLD = 18
DEFAULT_IMAGE_CONTRAST = 1.0
DEFAULT_IMAGE_BLUR_RADIUS = 0.0
DEFAULT_IMAGE_MASK_GROW_SHRINK = 0
DEFAULT_IMAGE_NOISE_CLEANUP = 0
